version: "3.7"
services:
  bot_postgres:
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - bot_postgres:/var/lib/postgresql/data

volumes:
  bot_postgres:
    name: job-alert-docker-postgres